name: Arduino CI
on: [push, pull_request]

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP8266
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266
      - name: Compile Sketch
        run: arduino-cli compile --fqbn esp8266:esp8266:d1_mini ./water_tank_switch